# Generated by Django 3.1.1 on 2020-09-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='user',
            new_name='user_profile',
        ),
    ]
