# Generated by Django 3.1.1 on 2020-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200912_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tarifa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
