# Generated by Django 3.1.1 on 2020-10-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201009_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
