# Generated by Django 3.1.1 on 2020-10-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201009_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
