# Generated by Django 3.1.1 on 2020-10-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201010_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='repatidor',
            new_name='repartidor',
        ),
    ]
